name: fyp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^4.0.0
  google_places_flutter: ^2.0.6
  shared_preferences: ^2.2.2
  http: ^1.1.0
  csv: ^5.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_ui_auth: ^1.17.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  uuid: ^4.1.0
  flutter_tts: ^4.2.3
  speech_to_text: ^7.0.0
  flutter_compass: ^0.8.1
  sensors_plus: ^6.1.1
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets\images\FYP LOGO.JPG
    - assets\gtfs\routes.txt
    - assets\gtfs\stops.txt
    - assets\gtfs\trips.txt
    - assets\gtfs\stop_times.txt
    - assets\gtfs\frequencies.txt
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

