// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCFT8B0QAblP8lh6PL_pBzEg4b_yUPpUI',
    appId: '1:994842832429:web:8900e8a203b992f607d2a4',
    messagingSenderId: '994842832429',
    projectId: 'fyp-project-26046',
    authDomain: 'fyp-project-26046.firebaseapp.com',
    storageBucket: 'fyp-project-26046.firebasestorage.app',
    measurementId: 'G-K0VWBY71HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR2kdX5kyFEsatr2tfLkzWf-xO-vfW3LY',
    appId: '1:994842832429:android:8668bf7e07fa6cf207d2a4',
    messagingSenderId: '994842832429',
    projectId: 'fyp-project-26046',
    storageBucket: 'fyp-project-26046.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9yNLBQiKcLGXXEKwGjClxVUfiGxU5nVA',
    appId: '1:994842832429:ios:17ffb747dd22c47107d2a4',
    messagingSenderId: '994842832429',
    projectId: 'fyp-project-26046',
    storageBucket: 'fyp-project-26046.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9yNLBQiKcLGXXEKwGjClxVUfiGxU5nVA',
    appId: '1:994842832429:ios:17ffb747dd22c47107d2a4',
    messagingSenderId: '994842832429',
    projectId: 'fyp-project-26046',
    storageBucket: 'fyp-project-26046.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );
}
